name: Deploy

on: [push]

jobs:
  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/api
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9 # package.jsonにpackageManagerをつけてもサブディレクトリのせいか、これがないとエラーになる
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: |
          pnpm run generate:json
          pnpm run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          workingDirectory: packages/api # working-directoryを付けていても必要
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy
